functions
define function
invoking function
passing the arguments     

In [1]:
def cake_baker(p,f,s):
  print("no of pieces=",p)
  print("flavour=",f)
  print("si9ze==",s)

cake_baker("5 ", "chocolate","2kg")
cake_baker("100 ", "vanilla","3kg")

no of pieces= 5 
flavour= chocolate
si9ze== 2kg
no of pieces= 100 
flavour= vanilla
si9ze== 3kg


In [2]:
def add(*args):
  sum=0
  for i in args:
    sum+=i
  return sum
print(add(1,2,3,4,5))

15


In [3]:
def greet(**kwargs):
  print("hello")
  for key, value in kwargs.items():
    print(value)

greet(name="priyanka", usn="01fe21bec007", branch="ece")

hello
priyanka
01fe21bec007
ece


In [4]:
def greet(**kwargs):
  print("hello")
  for key, value in kwargs.items():
    print(value,end=" ")

greet(name="priyanka", usn="01fe21bec007", branch="ece")

hello
priyanka 01fe21bec007 ece 

In [13]:
import random

x=random.randint(1,9)
print(x)

a=random.random()
print(a)

6
0.4089759412401671


In [20]:
import random

computer=random.randint(1,9)
userinput= int(input("enter the number between 1 and 9"))
print(computer)
print(userinput)

if computer>userinput:
  print("computer won")

elif computer==userinput:
  print("tie")

else:
  print("you won")


enter the number between 1 and 95
1
5
you won


In [27]:
from math import e
import random
gamelist=['rock','paper','scissors']
comp=random.choice(gamelist)
user=input("enter either rock or paper or scissor")
print(comp)
print(user)

if(comp=="rock" and user=="paper"):
  print("user won")
elif(comp=="paper" and user=="scissor"):
  print("user won")
elif(comp=="scissor" and user=="paper"):
  print("comp won")
elif(comp=="paper" and user=="rock"):
  print("comp won")
else:
  print("tie")


enter either rock or paper or scissorscissor
paper
scissor
user won


numpy-numerical python

In [29]:
import numpy as np
a=np.array([35,1,34,36,27,48,49])
print(type(a))

b=np.zeros(3)
c=np.ones(4)

print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 27 34 35 36 48 49]
